#! /bin/bash

# Load rbenv automatically
# eval "$(rbenv init -)"

if [ -r ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

if [ -r ~/.auth ]; then
  source ~/.auth
fi

# ---------------------------------------------------------------------------
# Plugins 
# ---------------------------------------------------------------------------
# Powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/local/lib/python3.8/site-packages/powerline/bindings/bash/powerline.sh

# -------------------------------
# ENVIRONMENT CONFIGURATION
# -------------------------------
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/sbin/:$PATH"
export BASH_SILENCE_DEPRECATION_WARNING=1

# Set Paths for python@3.8 first in the PATH environment
export PATH="/usr/local/opt/python@3.8/bin:$PATH"

# For compilers to find python@3.8
# export LDFLAGS="-L/usr/local/opt/python@3.8/lib"

# For pkg-config to find python@3.8
# export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig"

# Set Paths
# ------------------------------------------------------------
# export PATH="$PATH:/usr/local/bin/"
# export PATH="/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

# Set Default Editor (change 'Nano' to the editor of your choice)
# ------------------------------------------------------------
# export EDITOR=/usr/bin/nano

# Set default blocksize for ls, df, du
# from this: http://hints.macworld.com/comment.php?mode=view&cid=24491
# ------------------------------------------------------------
export BLOCKSIZE=1k

# Add color to terminal
# (this is all commented out as I use Mac Terminal Profiles)
# from http://osxdaily.com/2012/02/21/add-color-to-the-terminal-in-mac-os-x/
# ------------------------------------------------------------
# export CLICOLOR=1
# export LSCOLORS=ExFxBxDxCxegedabagacad
